name: tus_client_dart
description: A tus client for dart allowing resumable uploads using the tus protocol.
version: 1.0.6
homepage: https://github.com/tomassasovsky/tus_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cross_file: ^0.3.3
  http: ^0.13.4
  path: ^1.8.1

dev_dependencies:
  mockito: ^5.1.0
  build_runner: ^2.1.10
  test: ^1.21.1
